# Generated by Django 5.1.3 on 2024-12-03 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('IPDapp', '0001_initial'),
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioninfos',
            name='primary_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_doctor', to='testapp.doctortable'),
        ),
        migrations.AddField(
            model_name='admissioninfos',
            name='ref_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.hospitalmaster'),
        ),
        migrations.AddField(
            model_name='admissioninfos',
            name='secondary_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secoundry_doctor', to='testapp.doctortable'),
        ),
        migrations.AddField(
            model_name='admissioninfos',
            name='req_ward_cate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IPDapp.admissionwardcate'),
        ),
        migrations.AddField(
            model_name='admissionwardcategory',
            name='ward_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPDapp.admissionwardtype'),
        ),
        migrations.AddField(
            model_name='admissionwardcate',
            name='ward_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPDapp.admissionwardtype'),
        ),
        migrations.AddField(
            model_name='admissioninfos',
            name='req_ward_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IPDapp.admissionwardtype'),
        ),
        migrations.AddField(
            model_name='bed_transfer',
            name='from_ward_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_ward_type', to='IPDapp.admissionwardcate'),
        ),
        migrations.AddField(
            model_name='bed_transfer',
            name='from_ward_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_ward_type', to='IPDapp.admissionwardtype'),
        ),
        migrations.AddField(
            model_name='bed_transfer',
            name='to_ward_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_ward_type', to='IPDapp.admissionwardcate'),
        ),
        migrations.AddField(
            model_name='bed_transfer',
            name='to_ward_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_ward_type', to='IPDapp.admissionwardtype'),
        ),
        migrations.AddField(
            model_name='bedallotments',
            name='room_nos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.roomnumber'),
        ),
        migrations.AddField(
            model_name='bedmaster',
            name='ward_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPDapp.admissionwardcate'),
        ),
        migrations.AddField(
            model_name='bedmaster',
            name='ward_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPDapp.admissionwardtype'),
        ),
        migrations.AddField(
            model_name='bed_transfer',
            name='from_bed_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_bed_no', to='IPDapp.bedmastermain'),
        ),
        migrations.AddField(
            model_name='bed_transfer',
            name='to_bed_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_bed_no', to='IPDapp.bedmastermain'),
        ),
        migrations.AddField(
            model_name='admissioninfos',
            name='bed_no',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='IPDapp.bedmastermain'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPDapp.country'),
        ),
        migrations.AddField(
            model_name='doctor_transfer',
            name='from_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_dept', to='testapp.doctortable'),
        ),
        migrations.AddField(
            model_name='doctor_transfer',
            name='to_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_dept', to='testapp.doctortable'),
        ),
        migrations.AddField(
            model_name='bedmaster',
            name='floor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPDapp.floormaster'),
        ),
        migrations.AddField(
            model_name='admissionwardtype',
            name='floor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPDapp.floormaster'),
        ),
        migrations.AddField(
            model_name='admissionwardcate',
            name='floor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPDapp.floormaster'),
        ),
        migrations.AddField(
            model_name='doctor_transfer',
            name='from_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_doctor', to='IPDapp.ipd_dept'),
        ),
        migrations.AddField(
            model_name='doctor_transfer',
            name='to_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_doctor', to='IPDapp.ipd_dept'),
        ),
        migrations.AddField(
            model_name='admissioninfos',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='IPDapp.ipd_dept'),
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='IPDapp.city'),
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='IPDapp.country'),
        ),
        migrations.AddField(
            model_name='room_defination',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='testapp.roomnumber'),
        ),
        migrations.AddField(
            model_name='room_defination',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor', to='IPDapp.floormaster'),
        ),
        migrations.AddField(
            model_name='room_defination',
            name='nursing_counter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursecounter', to='IPDapp.nursingstationcounter'),
        ),
        migrations.AddField(
            model_name='room_defination',
            name='room_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='testapp.roomnumber'),
        ),
        migrations.AddField(
            model_name='room_defination',
            name='ward_cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardcate', to='IPDapp.admissionwardcate'),
        ),
        migrations.AddField(
            model_name='room_defination',
            name='ward_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardtype', to='IPDapp.admissionwardtype'),
        ),
        migrations.AddField(
            model_name='roommaster',
            name='floor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPDapp.floormaster'),
        ),
        migrations.AddField(
            model_name='bedmaster',
            name='room_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPDapp.roommaster'),
        ),
        migrations.AddField(
            model_name='admissionwardtype',
            name='room_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPDapp.roommaster'),
        ),
        migrations.AddField(
            model_name='admissionwardcate',
            name='room_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPDapp.roommaster'),
        ),
        migrations.AddField(
            model_name='room_defination',
            name='ward_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardname', to='IPDapp.wardname'),
        ),
        migrations.AddField(
            model_name='roommaster',
            name='wing_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPDapp.wingmaster'),
        ),
        migrations.AddField(
            model_name='room_defination',
            name='wing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wing', to='IPDapp.wingmaster'),
        ),
        migrations.AddField(
            model_name='floormaster',
            name='wing_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPDapp.wingmaster'),
        ),
        migrations.AddField(
            model_name='bedmaster',
            name='wing_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPDapp.wingmaster'),
        ),
    ]
