# Generated by Django 5.1.3 on 2024-12-03 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testapp', '0001_initial'),
        ('usermanagementapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_user_profile', to='usermanagementapp.screenaccess'),
        ),
        migrations.AddField(
            model_name='credit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='corporatemaster',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.designation'),
        ),
        migrations.AddField(
            model_name='diagnosissub',
            name='main_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.diagnosis'),
        ),
        migrations.AddField(
            model_name='citymaster',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.districtmaster'),
        ),
        migrations.AddField(
            model_name='doctoraccounting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctortable',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctortable',
            name='doctor_belogns_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.branchmaster'),
        ),
        migrations.AddField(
            model_name='doctorscheduletable',
            name='select_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.doctortable'),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='doctor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.doctortable'),
        ),
        migrations.AddField(
            model_name='centralisedadminview',
            name='Doc_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.doctortable'),
        ),
        migrations.AddField(
            model_name='appointmenttable',
            name='doctor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.doctortable'),
        ),
        migrations.AddField(
            model_name='advpatientvisitmains',
            name='nurse_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.doctortable'),
        ),
        migrations.AddField(
            model_name='emrinforecord',
            name='emrinfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emrinfo_record', to='testapp.emrinfo'),
        ),
        migrations.AddField(
            model_name='branchmaster',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.groupmaster'),
        ),
        migrations.AddField(
            model_name='insurance_checklist_child',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insurance_checklist_parent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insurance_claim_acknowledge',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insurance_payement_detail',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insurance_raising_queries',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detailed_itemstatus_temp',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.inventory_itemmaster'),
        ),
        migrations.AddField(
            model_name='department_consumption',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.inventory_itemmaster'),
        ),
        migrations.AddField(
            model_name='investigationproceduresub',
            name='main_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.diagnosis'),
        ),
        migrations.AddField(
            model_name='item_issue_child',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.inventory_itemmaster'),
        ),
        migrations.AddField(
            model_name='item_issue_temp',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.inventory_itemmaster'),
        ),
        migrations.AddField(
            model_name='item_issue_tosubstore_child',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.inventory_itemmaster'),
        ),
        migrations.AddField(
            model_name='item_return_child',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.inventory_itemmaster'),
        ),
        migrations.AddField(
            model_name='item_return_supplier_child',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.inventory_itemmaster'),
        ),
        migrations.AddField(
            model_name='item_return_tocpc_child',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.inventory_itemmaster'),
        ),
        migrations.AddField(
            model_name='item_status_particular_temp',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.inventory_itemmaster'),
        ),
        migrations.AddField(
            model_name='item_transfer_issue_temp',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.inventory_itemmaster'),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.itembelongstomaster'),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='item_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.itemcategorymaster'),
        ),
        migrations.AddField(
            model_name='itemsubcategorymaster',
            name='itemcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.itemcategorymaster'),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.itemunitmaster'),
        ),
        migrations.AddField(
            model_name='labresultentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labresultentry',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='item_return_tocpc_parent',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='item_return_supplier_parent',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='item_return_parent',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='item_issue_tosubstore_parent',
            name='issue_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_location1', to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='item_issue_tosubstore_parent',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='item_issue_tosubstore_parent',
            name='receive_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_location1', to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='item_issue_parent',
            name='issue_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_location', to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='item_issue_parent',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='item_issue_parent',
            name='receive_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_location', to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='insurance_raising_queries',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='insurance_payement_detail',
            name='location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='insurance_claim_acknowledge',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='insurance_checklist_parent',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='insurance_checklist_child',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='doctortable',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='doctoraccounting',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='department_consumption',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='credit',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='createuser',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_user_location', to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='bookedappointments',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='makeitem_return_temp',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.inventory_itemmaster'),
        ),
        migrations.AddField(
            model_name='makeitem_return_tocpc_temp',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.inventory_itemmaster'),
        ),
        migrations.AddField(
            model_name='makepo_pi_temp',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.inventory_itemmaster'),
        ),
        migrations.AddField(
            model_name='makepo_pi_temp',
            name='unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.itemunitmaster'),
        ),
        migrations.AddField(
            model_name='manual_stock_adjustment',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.inventory_itemmaster'),
        ),
        migrations.AddField(
            model_name='manual_stock_adjustment',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='material_intent_child',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.inventory_itemmaster'),
        ),
        migrations.AddField(
            model_name='material_intent_parent',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='material_intent_temp',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.inventory_itemmaster'),
        ),
        migrations.AddField(
            model_name='material_intent_temp',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='newappointmentbyadminchoosedoctor',
            name='doctor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.doctortable'),
        ),
        migrations.AddField(
            model_name='opdbillingmain',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opdbillingmain',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='opdbillingpackage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opdbillingpackage',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='opdbillingsub',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opdbillingsub',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='opdbillingtemper',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opdbillingtemper',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='opdbillsettlementtemp',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opdbillsettlementtemp',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='packing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.packagigmaster'),
        ),
        migrations.AddField(
            model_name='patientbillinginfos',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientbillinginfos',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='patientregistrationmains',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientregistrationmains',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='patientregistrationsub',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientregistrationsub',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='patientsregistrationsallinone',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientsregistrationsallinone',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='patientvisitmains',
            name='clinical_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.clinicalordepartment'),
        ),
        migrations.AddField(
            model_name='patientvisitmains',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientvisitmains',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.doctortable'),
        ),
        migrations.AddField(
            model_name='patientvisitmains',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='pendinginvestigation_main',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pendinginvestigation_main',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='prescriptiondialysis',
            name='dialysis_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.dialysate_type'),
        ),
        migrations.AddField(
            model_name='prescriptiondialysis',
            name='dialyzer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.dialyzer'),
        ),
        migrations.AddField(
            model_name='prescriptiondialysis',
            name='heparin_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.heparin_type'),
        ),
        migrations.AddField(
            model_name='presentingcomplaintsub',
            name='main_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.presentingcomplaint'),
        ),
        migrations.AddField(
            model_name='labtemplatemaster',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.profilemaster'),
        ),
        migrations.AddField(
            model_name='ps_countersale_child',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.inventory_itemmaster'),
        ),
        migrations.AddField(
            model_name='ps_countersale_parent',
            name='location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='ps_countersale_temp',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.inventory_itemmaster'),
        ),
        migrations.AddField(
            model_name='ps_countersale_temp_otc',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.inventory_itemmaster'),
        ),
        migrations.AddField(
            model_name='ps_sales_return_child',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.inventory_itemmaster'),
        ),
        migrations.AddField(
            model_name='purchase_intent_child',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.inventory_itemmaster'),
        ),
        migrations.AddField(
            model_name='purchase_intent_parent',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='purchase_intent_temp',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.inventory_itemmaster'),
        ),
        migrations.AddField(
            model_name='purchase_intent_temp',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='purchaseorder_child',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.inventory_itemmaster'),
        ),
        migrations.AddField(
            model_name='purchaseorder_child',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.itemunitmaster'),
        ),
        migrations.AddField(
            model_name='purchaseorder_parent',
            name='Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='purchaseorder_parent',
            name='po_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_location_name', to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='purchaseorder_temp',
            name='item_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.inventory_itemmaster'),
        ),
        migrations.AddField(
            model_name='purchaseorder_temp',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.itemunitmaster'),
        ),
        migrations.AddField(
            model_name='replicatedtokenmasterconf',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='replicatedtokenmasterconf',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='ris_pendinginvestigation_main',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ris_pendinginvestigation_main',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='ris_pendinginvestigation_main',
            name='uhid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.patientsregistrationsallinone'),
        ),
        migrations.AddField(
            model_name='ris_report',
            name='RIS_PendingInvestigation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.ris_pendinginvestigation_main'),
        ),
        migrations.AddField(
            model_name='ris_report',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ris_report',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='centralisedadminview',
            name='room_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.roomnumber'),
        ),
        migrations.AddField(
            model_name='samplecollected',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='samplecollected',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='samplecollection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='samplecollection',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='profilechargemaster',
            name='ward_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.servicecategory'),
        ),
        migrations.AddField(
            model_name='opdbillingtemper',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.servicecategory'),
        ),
        migrations.AddField(
            model_name='servicechargemaster',
            name='ward_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.servicecategory'),
        ),
        migrations.AddField(
            model_name='purchaseorder_parent',
            name='Department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.servicedepartment'),
        ),
        migrations.AddField(
            model_name='purchase_intent_temp',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.servicedepartment'),
        ),
        migrations.AddField(
            model_name='purchase_intent_parent',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.servicedepartment'),
        ),
        migrations.AddField(
            model_name='material_intent_temp',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.servicedepartment'),
        ),
        migrations.AddField(
            model_name='material_intent_parent',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.servicedepartment'),
        ),
        migrations.AddField(
            model_name='item_issue_tosubstore_parent',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.servicedepartment'),
        ),
        migrations.AddField(
            model_name='item_issue_parent',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.servicedepartment'),
        ),
        migrations.AddField(
            model_name='inventory_itemmaster',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.servicedepartment'),
        ),
        migrations.AddField(
            model_name='department_consumption',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.servicedepartment'),
        ),
        migrations.AddField(
            model_name='createuser',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.servicedepartment'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='service_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.servicecategory'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='service_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.servicedepartment'),
        ),
        migrations.AddField(
            model_name='ris_pendinginvestigation_main',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.servicemaster'),
        ),
        migrations.AddField(
            model_name='radiologytemplatemaster',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.servicemaster'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='service_sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.servicesubcategory'),
        ),
        migrations.AddField(
            model_name='servicechargemaster',
            name='ward_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.servicesubcategory'),
        ),
        migrations.AddField(
            model_name='profilechargemaster',
            name='ward_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.servicesubcategory'),
        ),
        migrations.AddField(
            model_name='opdbillingtemper',
            name='service_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.servicesubcategory'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='ServiceSubDepartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.servicesubdepartment'),
        ),
        migrations.AddField(
            model_name='slipcreation',
            name='Doctor_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.doctortable'),
        ),
        migrations.AddField(
            model_name='slipcreation',
            name='Room_No',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.roomnumber'),
        ),
        migrations.AddField(
            model_name='stock_batchwise',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.servicedepartment'),
        ),
        migrations.AddField(
            model_name='stock_batchwise',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.inventory_itemmaster'),
        ),
        migrations.AddField(
            model_name='stock_batchwise',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='stock_batchwise',
            name='po_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stb_location_name', to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='stock_batchwise_mainstore',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.servicedepartment'),
        ),
        migrations.AddField(
            model_name='stock_batchwise_mainstore',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.inventory_itemmaster'),
        ),
        migrations.AddField(
            model_name='stock_batchwise_mainstore',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='stock_batchwise_mainstore',
            name='receive_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stbm_location_name', to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='stockentry_child',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.inventory_itemmaster'),
        ),
        migrations.AddField(
            model_name='stockentry_parent',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.servicedepartment'),
        ),
        migrations.AddField(
            model_name='stockentry_parent',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='stockentry_parent',
            name='po_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='se_location_name', to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='stockentry_temp',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.inventory_itemmaster'),
        ),
        migrations.AddField(
            model_name='storemaster',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.servicedepartment'),
        ),
        migrations.AddField(
            model_name='storemaster',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='stockentry_temp',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='stockentry_parent',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='stock_batchwise_mainstore',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='stock_batchwise',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='purchaseorder_parent',
            name='store_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='purchase_intent_temp',
            name='cpc_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_temp_store', to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='purchase_intent_temp',
            name='main_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='purchase_intent_parent',
            name='cpc_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_indent_store', to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='purchase_intent_parent',
            name='main_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='ps_countersale_parent',
            name='store_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='material_intent_temp',
            name='main_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='material_intent_temp',
            name='substore_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_temp_store', to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='material_intent_parent',
            name='main_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='material_intent_parent',
            name='substore_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_indent_store', to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='manual_stock_adjustment',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='item_return_tocpc_parent',
            name='indent_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indent_store', to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='item_return_tocpc_parent',
            name='receiving_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_return_receive_store', to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='item_return_tocpc_parent',
            name='return_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_return_cpc_store', to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='item_return_supplier_parent',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='item_return_parent',
            name='receiving_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='item_return_parent',
            name='return_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_return_store', to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='item_issue_tosubstore_parent',
            name='issued_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_store1', to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='item_issue_tosubstore_parent',
            name='received_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='item_issue_tosubstore_child',
            name='issued_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='item_issue_parent',
            name='issued_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_indent_store1', to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='item_issue_parent',
            name='received_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='department_consumption',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='createuser',
            name='store',
            field=models.ManyToManyField(blank=True, related_name='create_user_store', to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='tariffchargemaster',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.tariffmaster'),
        ),
        migrations.AddField(
            model_name='servicechargemaster',
            name='tariff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.tariffmaster'),
        ),
        migrations.AddField(
            model_name='profilechargemaster',
            name='tariff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.tariffmaster'),
        ),
        migrations.AddField(
            model_name='packagechargemaster',
            name='tariff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.tariffmaster'),
        ),
        migrations.AddField(
            model_name='billinggrouptarifflink',
            name='Tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.tariffmaster'),
        ),
        migrations.AddField(
            model_name='timetaken',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetaken',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='tokencreationdone',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tokencreationdone',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='tokencreations',
            name='Doct_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.doctortable'),
        ),
        migrations.AddField(
            model_name='tokencreations',
            name='Room_No',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.roomnumber'),
        ),
        migrations.AddField(
            model_name='slipcreation',
            name='select_token_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.tokencreations'),
        ),
        migrations.AddField(
            model_name='tokenmasterconf',
            name='Doct_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DoctorTable', to='testapp.doctortable'),
        ),
        migrations.AddField(
            model_name='tokenmasterconf',
            name='Room_No',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.roomnumber'),
        ),
        migrations.AddField(
            model_name='tokenmasterconf',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tokenmasterconf',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='transfer_intent_child',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.inventory_itemmaster'),
        ),
        migrations.AddField(
            model_name='transfer_intent_parent',
            name='cpc_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trnasfer_indent_store', to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='transfer_intent_parent',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.servicedepartment'),
        ),
        migrations.AddField(
            model_name='transfer_intent_parent',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='transfer_intent_parent',
            name='main_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='transfer_intent_temp',
            name='cpc_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trnasfer_temp_store', to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='transfer_intent_temp',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.servicedepartment'),
        ),
        migrations.AddField(
            model_name='transfer_intent_temp',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.inventory_itemmaster'),
        ),
        migrations.AddField(
            model_name='transfer_intent_temp',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='transfer_intent_temp',
            name='main_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='transfer_request_mainstore_child',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.inventory_itemmaster'),
        ),
        migrations.AddField(
            model_name='transfer_request_mainstore_parent',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.servicedepartment'),
        ),
        migrations.AddField(
            model_name='transfer_request_mainstore_parent',
            name='indent_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='transfer_request_mainstore_parent',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='transfer_request_mainstore_parent',
            name='request_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_request_store', to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='vendor_payment',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.servicedepartment'),
        ),
        migrations.AddField(
            model_name='vendor_payment',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='vendor_payment',
            name='po_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vp_location_name', to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='vendor_payment',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='vendor_payment',
            name='vendor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.vendormaster'),
        ),
        migrations.AddField(
            model_name='stockentry_parent',
            name='vendar_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.vendormaster'),
        ),
        migrations.AddField(
            model_name='stock_batchwise_mainstore',
            name='vendor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.vendormaster'),
        ),
        migrations.AddField(
            model_name='stock_batchwise',
            name='vendar_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.vendormaster'),
        ),
        migrations.AddField(
            model_name='purchaseorder_parent',
            name='vendar_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.vendormaster'),
        ),
        migrations.AddField(
            model_name='item_return_supplier_parent',
            name='vendor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.vendormaster'),
        ),
        migrations.AddField(
            model_name='patientvisitmains',
            name='visit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.visittyoemaster'),
        ),
        migrations.AddField(
            model_name='advpatientvisitmains',
            name='visit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.visittyoemaster'),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='tariffchargemaster',
            name='Ward_Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.wardcategory'),
        ),
        migrations.AddField(
            model_name='packagechargemaster',
            name='ward_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.wardcategory'),
        ),
        migrations.AddField(
            model_name='tariffchargemaster',
            name='Ward_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.wardtype'),
        ),
        migrations.AddField(
            model_name='packagechargemaster',
            name='ward_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.wardtype'),
        ),
    ]
