from django.urls import path,include
from testapp import  views,qms_views,pharmacyviews
urlpatterns=[
    # path('',views.patient_view),
    # path('',views.email_sending),
    path('book-appointment',views.book_appointment),
    path('book-appointment/<int:npp>',views.book_appointment),
    path('mobile_register',views.mobile_register),
    path('date_time',views.date_time),
    path('appointment_detail',views.appointment_detail),
    path('booking_detail',views.booking_detail),
    path('doctor-view',views.doctor_view),
    path('doctor-schedule-view',views.doctor_schedule_view),
    path('appointment-view',views.appointment_view),
    path('patient-view',views.patient_view_detail),
    path('a_dashboard',views.patient_dashboard),
    path('admin_list_table',views.admin_list_table),
    path('patient_table',views.patient_table),
    path('doctor_table',views.DoctorDashbordView.as_view(),name='delete'),
    path('edit-doctor/<str:pk>',views.DoctorEditView.as_view()),
    path('detail-doctor/<str:pk>',views.DoctorDetailView.as_view()),
    path('delete-appointment/<str:pk>',views.AppointmentDeleteView.as_view()),
    path('detail-appointment/<str:pk>',views.AppointmentDetailView.as_view()),
    path('success-booked',views.success_booked),
    path('doctor-schedule',views.doctor_schedule_view),
    path('schedule-date',views.schedule_date),
    path('time-scheduling',views.time_scheduling),
    path('scheduled_time',views.scheduled_time),
    #cancel appointment
    path('cancel-appointment/<str:patient_id>',views.cancel_appointment),
    #Appointment_dashboard
    path('doctor_dash',views.doctor_dash),
    path('doctor_appointment',views.doctor_appointment),
    path('prescription',views.prescription),
    path('appointment_list',views.appointment_list),
    path('patient_list',views.patient_list),
    #Interface
    path('interface_dashboard',views.interface_dashboard),
    path('patient',views.patient),
    path('lo_g_in',views.login),
    path('table',views.table),
    #reports
    path('reports',views.reports),
    path('cancellation-reports',views.cancellation_reports),
    path('shorting-filter',views.shorting_filter),
    path('appointment-detail-reports',views.appointment_detail_reports),
    #doctor-admin pannel
    path('doctor-admin-pannel',views.doctor_admin_pannel),
    path('create-admin',views.sign_up_form),
    #=======New Appointment======
    path('filtering-department',views.filtering_department),
    #===========QMS=======================
    # path('qms',qms_views.Token_Master_Cofiguration.as_view()),
    path('qms/',qms_views.Token_Master_Cofiguration_Class.as_view()),
    path('qms/<pk>',qms_views.Token_Master_Cofiguration_ClassRUD.as_view()),
    path('qms-token-master',qms_views.Token_Master_Cofiguration_view.as_view()),

    #==========title master======================
    path('titile-master',views.titile_master),
    path('add-new-title',views.add_new_title),
    path('edit-title',views.edit_title),
    path('edit-title/<pk>',views.editing_title),
    path('hospital-master',views.hospital_master),
    path('add-new-hospital',views.add_new_hospital),
    path('edit-hospital-master',views.edit_hospital_master),
    path('edit-hospital-master/<pk>',views.editing_hospital_master),
    path('add-new-gender-master',views.add_new_gender_master),
    path('edit-gender-master',views.edit_gender_master),
    path('editing-gender-master/<pk>',views.editing_gender_master),
    path('holiday_master',views.holiday_master),
    path('edit_holiday_master',views.edit_holiday_master),
    path('edit_holiday_master/<pk>',views.editing_holiday_master),
    path('most_common_document',views.most_common_document),
    path('edit_most_common_document',views.edit_most_common_document),
    path('editing_most_common_document/<pk>',views.editing_most_common_document),
    #Master related urls
    #General_master
    path('title_master',views.title_master),#Done
    # path('hospital_master',views.hospital_master),
    path('relation',views.relation),#Done
    path('edit_relation',views.edit_relation),
    path('editing_relation/<pk>',views.editing_relation),
    path('city_master',views.city_master),
    path('edit_city_master',views.edit_city_master),
    path('editing_city_master/<pk>',views.editing_city_master),
    path('country_master',views.country_master),
    path('edit-country',views.edit_country_master),
    path('editing-country/<pk>',views.editing_country_master),
    path('district',views.district),
    path('edit-district',views.edit_district),
    path('editing-district/<pk>',views.editing_district),
    path('gender_master',views.gender_master),#Done
    path('maritial_status',views.maritial_status),#Done
    path('edit_maritial_status',views.edit_maritial_status),
    path('editing_maritial_status/<pk>',views.editing_maritial_status),
    #Service Master
    path('service_master',views.service_master),
    path('edit_service_master/<pk>',views.edit_service_master),
    path('tariff_master',views.tariff_master),
    path('edit_tariff_master',views.edit_tariff_master),
    path('edit_billing_master',views.edit_billing_master),
    path('editing_billing_master/<int:id>',views.editing_billing_master),
    path('editing_tariff_master/<pk>',views.editing_tariff_master),
    path('corporate_master',views.corporate_master),
    path('edit_corporate_master',views.edit_corporate_master),
    path('editing_corporate_master/<pk>',views.editing_corporate_master),
    path('billing_master',views.billing_master),
    path('tariff_charge_master',views.tariff_charge_master),
    path('edit_tariff_charge_master',views.edit_tariff_charge_master),
    path('editing_tariff_charge_master/<pk>',views.editing_tariff_charge_master),
    path('add_charge',views.add_charge),
    path('billing_group_tariff',views.billing_group_tariff),
    path('master-dashboard',views.master_dashboard),
    #==============Advance QMS Master=====================
    path('service-master',views.add_service_master),
    path('add_sub_service_master',views.add_sub_service_master),
    path('add_service_department',views.add_service_department),
    path('add_service_sub_department', views.add_service_sub_department),
    path('edit_add_service_sub_department', views.edit_add_service_sub_department),
    path('editing_add_sub_service_department/<int:id>', views.editing_add_service_sub_department),
    path('ward_category',views.ward_category),
    path('ward_type',views.ward_type),
    path('edit_ward_type', views.edit_ward_type),
    path('editing_ward_type/<int:id>', views.editing_ward_type),
    path('blood_master', views.blood_master),
    path('edit_blood_master', views.edit_blood_master),
    path('editing_blood_master/<int:id>', views.editing_blood_master),
    path('designation',views.designation),
    # ===============diagnosis master===================
    path('diagnosis_master',views.diagnosis_master),
    #==============URL FOR QMS=====================
    path('qms_dashboard',views.qms_dashboard,name='qms_dashboard'),#Done
    path('token_master_configuration',views.token_master_configuration),#Done
    path('token_master_configuration/<pk>',views.token_master_configuration_update),#Done
    path('token_creation',views.token_creation),#Done
    path('token_creation2',views.token_creation2),#Done
    path('token_slip_generation/<pk>',views.token_slip_generation),#Done
    path('token_slip_generations',views.token_slip_generations),#Done
    path('centralised_admin_view',views.centralised_admin_view),#Most Done
    path('opd_reception_view',views.opd_reception_view),
    path('qms_dashboard',views.qms_dashboard),

    #==============Advance QMS Master=====================
    path('create-room',views.create_room),
    # Clinical Dashboard (Main DashBoard)
    path('dashboard',views.dashboard,name='dashboard'),
    path('partially_dashboard',views.partially_dashboard),
    path('patient_registration/',views.patient_registration),
    path('patient_registration/<str:uhid>',views.patient_registration_edit),
    path('register_card/',views.register_card),
    path('register_card/<str:uhid>',views.register_card_generation),
    path('patient_visit/',views.patient_visit),
    path('nursing_assessment/<str:data>', views.nursing_assessment),
    # path('nursing_assessment/',views.nursing_assessment),
    path('opd_billing/',views.opd_billing,name='ob'),
    path('opd_billing_search/<str:uhid>',views.opd_billing),
    path('opd_billing_search',views.opd_billing_search),
    path('visit_dashboard/',views.visit_dashboard),
    path('opdbillrecipte/',views.opdbillrecipte),
    # Image Uploading
    path('image_uploading',views.image_uploading),
    path('patient_search/',views.patient_search),
    path('patient_search_edit/<str:uhid>',views.patient_search_edit),
    path('patient_search_delete/<str:uhid>',views.patient_search_delete),
    path('out_paient_visit',views.out_paient_visit),
    # Master
    path('branch_master',views.branch_master),
    path('group_master',views.group_master),
    path('visit_type_master',views.visit_type_master),
    # Nurse Station
    path('nurse_dashboard/',views.nurse_dashboard),
    path('nurse_login/',views.nurse_login),
    path('emergency/',views.emergency),
    path('in_patient_management/',views.in_patient_management),
    path('procedure_room/',views.procedure_room),
    path('system_control/',views.system_control),
#     User Management
    path('billing_group_corporate',views.billing_group_corporate),

    path('edit_wardcategory',views.edit_wardcategory),
    path('editing_wardcategory/<pk>',views.editing_wardcategory),
    path('intelligence_search',views.intelligence_search),
#     Search Address
    path('search',views.search_address,name='search'),
# Inventory

    path('item_master',views.item_master),

    path('item_manufacturer',views.item_manufacturer),
    path('store_nursing_counter_mapping',views.store_nursing_counter_mapping),
    path('item_location_master',views.item_location_master),
    path('multi_row',views.multi_row),

#=====================Clinic Management================
    path('cm/<str:data>',views.clinical_managements),
# ====================All Master Start==================
    path('visit_type_master',views.visit_type_master),
    path('edit_visit_type_master',views.edit_visit_type_master),
    path('editing_visit_type_master/<int:id>',views.editing_visit_type_master),
    path('add_sub_service_master',views.add_sub_service_master),
    path('edit_add_sub_service_master',views.edit_add_sub_service_master),
    path('editing_add_sub_service_master/<int:id>',views.editing_add_sub_service_master),
    path('add_service_department',views.add_service_department),
    path('edit_add_service_department',views.edit_add_service_department),
    path('editing_add_service_department/<int:id>',views.editing_add_service_department),
    path('designation',views.designation),
    path('edit_designation',views.edit_designation),
    path('editing_designation/<int:id>',views.editing_designation),
    path('clinical_department',views.clinical_department),
    path('edit_clinical_department',views.edit_clinical_department),
    path('editing_clinical_department/<int:id>',views.editing_clinical_department),
    path('create-room',views.create_room),
    path('edit_create_room',views.edit_create_room),
    path('editing_create_room/<int:id>',views.editing_create_room),
#======================All Master End======================
    path('temp_service_removing/<int:id>',views.temp_service_removing,name='ser'),
    path('opd_trasaction',views.opd_trasaction,name='opd_trasaction'),
# =================== by mantu ===================
    path('opd_payment_mode', views.opd_payment_mode),
    path('opd_payment_credit', views.opd_payment_credit),
    path('service_charge_master', views.service_charge_master),
    path('main_opd', views.main_opd),
    # path('delete_everything', views.delete_everything),
    path('ipd', views.ipd_list),
    path('summerize_bill', views.summerize_bill),
    path('details_bill', views.details_bill),
    path('payment_mode', views.payment_mode),
    path('edit_payment_mode', views.edit_payment_mode),
    path('editing_payment_mode/<str:pk>/', views.editing_payment_mode),
    path('bank_master', views.bank_master),
    path('edit_bank_master', views.edit_bank_master),
    path('editing_bank_master/<str:pk>/', views.editing_bank_master),
    path('investigation_view', views.investigation_view),
    path('get_list_patient', views.get_list_patient),
    path('get_list_patient_edit/<str:uhid>/', views.get_list_patient_edit),
    path('avd_pay_paient_visit', views.avd_pay_paient_visit),
    # date 10/11/22=====================
    path('hospital_report_revenue', views.hospital_report_revenue),
    path('department_wise_reports', views.department_wise_reports),
    path('patient_details', views.patient_details),
    path('detail_revenue_report', views.detail_revenue_report),
    path('hospital_department_report', views.hospital_department_report),
    path('all_details_report', views.all_details_report),
    path('doctor_wise_revenue_report', views.doctor_wise_revenue_report),
    path('service_analysis_report', views.service_analysis_report),
    path('detail_doctor_report', views.detail_doctor_report),
    path('today_report', views.today_report),
    path('credit_bill', views.credit_bill),
    path('credit_patient', views.credit_patient),
    path('outstannding_amt_register', views.outstannding_amt_register),
    path('payer_by_report', views.payer_by_report),
    path('report_datewise_bill', views.report_datewise_bill),
    path('mode_of_payment', views.mode_of_payment),
    # ============== opd package  =============
    path('opd_package_master', views.opd_package_master, name='opd_package_master'),
    path('opd_package_master_view', views.opd_package_master_view, name='opd_package_master_view'),
    path('opd_package_master_edit/<pk>', views.opd_package_master_edit, name='opd_package_master_edit'),
    path('opd_package_service', views.opd_package_service, name='opd_package_service'),
    path('opd_package_service_add', views.opd_package_service_add, name='opd_package_service_add'),
    path('opd_package_service_temp/<serv>', views.opd_package_service_temp, name='opd_package_service_temp'),

    #====================== API Karan 31/12/22 =====================
    path('api_medication', views.api_medication),
    path('api_medication_view', views.api_medication_view),
    path('api_PatientsRegistration/<pk>', views.api_PatientsRegistration),
    path('api_PatientsRegistration_view', views.api_PatientsRegistration_view),
    path('admissioninfo_all', views.admissioninfo_all),

    # ===================== For Bed Karan =====================
    path('bed_view', views.bed_view),
    path('bed_load', views.bed_load, name='bed_load'),

    path('doctor_ability_report', views.doctor_ability_report, name='doctor_ability_report'),
    path('bed_charge', views.bed_charge, name='bed_charge'),
    path('single_bed_charge_load', views.single_bed_charge_load, name='single_bed_charge_load'),
    path('Bed_charge_edit', views.Bed_charge_edit, name='Bed_charge_edit'),

    path('bed_charge_slip', views.bed_charge_slip, name='bed_charge_slip'),
    path('bed_charge_slip_details/<pk>', views.bed_charge_slip_details, name='bed_charge_slip_details'),
    path('charge_slip_load', views.charge_slip_load, name='charge_slip_load'),
    path('bed_charge_slip_details_edit/<pk>', views.bed_charge_slip_details_edit, name='bed_charge_slip_details_edit'),
    path('bed_charge_slip_details_editing/<pk>', views.bed_charge_slip_details_editing,
         name='bed_charge_slip_details_editing'),


    path('discharge_report', views.discharge_report, name='discharge_report'),

#=============================== opd package link with tariff =======================
    path('link_opdpackage_tariff',views.link_opdpackage_tariff),
    path('admission_load',views.admission_load),
    path('load_ward_category',views.load_ward_category),
    path('doctor_accounting',views.doctor_accounting),
    path('dr_accounting_report',views.dr_accounting_report),
    path('all_data_insert',views.all_data_insert),

# Profile Master 14/12/22
    path('profile_master',views.profile_master),
    path('profile_master_view',views.profile_master_view),
    path('profile_master_edit/<pk>/',views.profile_master_edit),
    path('profile_service', views.profile_service, name='profile_service'),
    path('profile_service_add', views.profile_service_add, name='profile_service_add'),
    path('profile_service_temp/<serv>', views.profile_service_temp, name='profile_service_temp'),
    path('service_test1/<dep>/<subdep>/', views.service_test_search, name='service_test_search'),
    path('service_test', views.service_test, name='service_test'),
    path('service_test_range/<pk>/', views.service_test_range, name='service_test_range'),
    path('service_test_range_edit/<pk>/', views.service_test_range_edit, name='service_test_range_edit'),
    path('service_test_edit', views.service_test_edit, name='service_test_edit'),
    path('service_test_editing/<pk>', views.service_test_editing, name='service_test_editing'),
    path('profile_package_tarifflink', views.profile_package_tarifflink, name='profile_package_tarifflink'),
    path('service_test_tarifflink', views.service_test_tarifflink, name='service_test_tarifflink'),

    path('sample_master',views.sample_master,name='sample_master'),
    path('volume_master',views.volume_master,name='volume_master'),
    path('sample_master_edit',views.sample_master_edit,name='sample_master_edit'),
    path('sample_master_editing/<pk>',views.sample_master_editing,name='sample_master_editing'),
    path('volume_master_edit',views.volume_master_edit,name='volume_master_edit'),
    path('volume_master_editing/<pk>',views.volume_master_editing,name='volume_master_editing'),

    path('lab_pending_investigation',views.lab_pending_investigation,name='lab_pending_investigation'),
    path('lab_sammple_collected',views.lab_sammple_collected,name='lab_sammple_collected'),
    path('lab_result_entry/<pk>',views.lab_result_entry,name='lab_result_entry'),
    path('result_validation',views.result_validation,name='result_validation'),
    path('result_validation_view/<pk>',views.result_validation_view,name='result_validation_view'),
    path('lab_report',views.lab_report,name='lab_report'),
    path('lab_report_print/<pk>',views.lab_report_print,name='lab_report_print'),
    path('dep_lab_report_print/<pk>',views.dep_lab_report_print,name='dep_lab_report_print'),
    path('dep_lab_report',views.dep_lab_report,name='dep_lab_report'),
    path('report_change/<pk>',views.report_change,name='report_change'),

# ============== user management ====================
    path('user_login',views.user_login_main,name='user_login_main'),
    path('',views.user_login_main,name='user_login_main'),
    # path('create_admin',views.create_admin,name='create_admin'),
    path('create_userprofile',views.create_userprofile,name='userprofile'),
    path('view_create_userprofile',views.view_create_userprofile,name='view_create_userprofile'),
    path('edit_create_userprofile/<pk>',views.edit_create_userprofile,name='edit_create_userprofile'),
    path('search_create_user',views.search_create_user,name='search_create_user'),
    path('create_user_delete/<pk>',views.create_user_delete,name='create_user_delete'),
    path('login',views.log_out,name='log_out'),


# ============== ward module =============
    path('paitent_ward',views.paitent_ward,name='ward'),
    path('paitent_ward_actions/<str:pk>/',views.paitent_ward_actions,name='paitent_ward_actions'),
    path('medication/<pk>',views.medication,name='medication'),
    path('medication/<pk>/<med>',views.medications,name='medication'),
    path('investigation/<pk>',views.investigation,name='investigation'),
    path('investigation_insert/<pk>/<ser>',views.investigation_insert,name='investigation_insert'),
    path('consultation/<pk>',views.consultation,name='consultation'),
    path('consultation_insert/<pk>/<ser>',views.consultation_insert,name='consultation_insert'),
    path('procedure/<pk>',views.procedure,name='procedure'),
    path('procedure_insert/<pk>/<ser>',views.procedure_insert,name='procedure_insert'),
    # 29/12/22 mantu ============================
    path('temp_records', views.temp_records, name='temp_records'),
    path('opd_billing_temp/', views.opd_billing_temp),
    # path('opd_billing_temp/<str:uhid>/', views.opd_billing_temp),
    path('opd_billing_temp/<str:uhid>/<vis>', views.opd_billing_temp),
    path('opdbill_all', views.opdbill_all, name='opdbill_all'),

    # ================ Doctor Share with Package 27/12/22 ==================================
    path('dr_share_with_package', views.dr_share_with_package),
    path('dr_share_with_profile', views.dr_share_with_profile),
    path('composite_services', views.composite_services),
    path('add_charge_profile', views.add_charge_profile),
    path('package_services', views.package_services),
    path('add_charge_package_services', views.add_charge_package_services),
    path('belongs_to_master', views.belongs_to_master),

    path('nursing_notes', views.nursing_notes),
    path('view_nursing_notes/<pk>', views.view_nursing_notes),

    #============= Dialysis Template ============= 23/01/23 ==========
    path('pre_dialysis_details/<pk>', views.pre_dialysis_details),
    path('view_pre_dialysis_details/<pk>/', views.view_pre_dialysis_details),
    path('post_dialysis_details/<pk>/', views.post_dialysis_details),
    path('view_post_dialysis/<pk>/', views.view_post_dialysis),
    path('dialysis_details/<pk>/', views.dialysis_details),
    path('chemotherapy_treatment_sheet', views.chemotherapy_treatment_sheet),
    path('view_chemotherapy/<pk>', views.view_chemotherapy),
    #======================== GOKILA CODE ======================
    # Reports
    path('Patient_registration_report', views.Patient_registration_report),
    path('Patient_registration_summery_report', views.Patient_registration_summery_report),
    path('appointment_report', views.appointment_report),
    path('patientvisit_report', views.patientvisit_report),
    path('consultant_report', views.consultant_report),
    path('grouping_admission_report', views.grouping_admission_report),
    path('Bed_Transfer_report', views.Bed_Transfer_report),
    path('bed_occupancy_report', views.bed_occupancy_report),
    path('bedview', views.bed_view),
    path('detail_bed_occupany_report', views.detail_bed_occupany_report),
    # estimate ====================
    path('estimate',views.estimate,name='estimate'),
    path('estimate_temp',views.estimate_temp,name='estimate_temp'),
    path('estimate_sub_temp/<str:serv>/',views.estimate_sub_temp,name='estimate_sub_temp'),
    path('estimate_pdf',views.estimate_pdf,name='estimate_pdf'),

    path('dashboard_report',views.dashboard_report,name='dashboard_report'),

    #======== Dialysis Master 01/02/2023 ================
    path('status_dialysis_view',views.status_dialysis_view,name='status_dialysis_view'),
    path('status_dialysis',views.status_dialysis,name='status_dialysis'),
    path('status_dialysis_edit/<pk>',views.status_dialysis_edit,name='status_dialysis_edit'),
    path('primary_dialysis_theropist',views.primary_dialysis_theropist,name='primary_dialysis_theropist'),
    path('primary_dialysis_theropist_view',views.primary_dialysis_theropist_view,name='primary_dialysis_theropist_view'),
    path('primary_dialysis_theropist_edit/<pk>',views.primary_dialysis_theropist_edit,name='primary_dialysis_theropist_edit'),
    path('secondry_dialysis_theropist',views.secondry_dialysis_theropist,name='secondry_dialysis_theropist'),
    path('secondry_dialysis_theropist_view',views.secondry_dialysis_theropist_view,name='secondry_dialysis_theropist_view'),
    path('secondry_dialysis_theropist_edit/<pk>',views.secondry_dialysis_theropist_edit,name='secondry_dialysis_theropist_edit'),    path('secondry_dialysis_theropist',views.secondry_dialysis_theropist,name='secondry_dialysis_theropist'),

    path('machine_name',views.machine_name,name='machine_name'),
    path('machine_name_view',views.machine_name_view,name='machine_name_view'),
    path('machine_name_edit/<pk>',views.machine_name_edit,name='machine_name_edit'),
    path('asset_type',views.asset_type,name='asset_type'),
    path('asset_type_view',views.asset_type_view,name='asset_type_view'),
    path('asset_type_edit/<pk>',views.asset_type_edit,name='asset_type_edit'),
    path('bruit_thrill',views.bruit_thrill,name='bruit_thrill'),
    path('bruit_thrill_view',views.bruit_thrill_view,name='bruit_thrill_view'),
    path('bruit_thrill_edit/<pk>',views.bruit_thrill_edit,name='bruit_thrill_edit'),
    path('access_site',views.access_site,name='access_site'),
    path('access_site_view',views.access_site_view,name='access_site_view'),
    path('access_site_edit/<pk>',views.access_site_edit,name='access_site_edit'),
    path('dialysis_type',views.dialysis_type,name='dialysis_type'),
    path('dialysis_type_view',views.dialysis_type_view,name='dialysis_type_view'),
    path('dialysis_type_edit/<pk>',views.dialysis_type_edit,name='dialysis_type_edit'),
    path('completion_Status',views.completion_Status,name='completion_Status'),
    path('completion_Status_view',views.completion_Status_view,name='completion_Status_view'),
    path('completion_Status_edit/<pk>',views.completion_Status_edit,name='completion_Status_edit'),
    path('needle_type',views.needle_type,name='needle_type'),
    path('needle_type_view',views.needle_type_view,name='needle_type_view'),
    path('needle_type_edit/<pk>',views.needle_type_edit,name='needle_type_edit'),
    path('dialyzer',views.dialyzer,name='dialyzer'),
    path('dialyzer_view',views.dialyzer_view,name='dialyzer_view'),
    path('dialyzer_edit/<pk>',views.dialyzer_edit,name='dialyzer_edit'),
    path('rating',views.rating,name='rating'),
    path('rating_view',views.rating_view,name='rating_view'),
    path('rating_edit/<pk>',views.rating_edit,name='rating_edit'),
    path('anticoagulation',views.anticoagulation,name='anticoagulation'),
    path('anticoagulation_view',views.anticoagulation_view,name='anticoagulation_view'),
    path('anticoagulation_edit/<pk>',views.anticoagulation_edit,name='anticoagulation_edit'),
    path('heparin_type',views.heparin_type,name='heparin_type'),
    path('heparin_type_view',views.heparin_type_view,name='heparin_type_view'),
    path('heparin_type_edit/<pk>',views.heparin_type_edit,name='heparin_type_edit'),
    path('closing_attendent',views.closing_attendent,name='closing_attendent'),
    path('closing_attendent_view',views.closing_attendent_view,name='closing_attendent_view'),
    path('closing_attendent_edit/<pk>',views.closing_attendent_edit,name='closing_attendent_edit'),
    path('shift', views.shift, name='shift'),
    path('shift_view', views.shift_view, name='shift_view'),
    path('shift_edit/<pk>', views.shift_edit, name='shift_edit'),
    path('schedule_master', views.schedule_master, name='schedule_master'),
    path('schedule_master_view', views.schedule_master_view, name='schedule_master_view'),
    path('schedule_master_edit/<pk>', views.schedule_master_edit, name='schedule_master_edit'),

    path('medical_equipment', views.medical_equipment, name='medical_equipment'),
    path('medical_equipment_edit/<pk>', views.medical_equipment_edit, name='medical_equipment_edit'),
    path('new_invoice', views.new_invoice, name='new_invoice'),
    path('maintanence_deatils', views.maintanence_deatils, name='maintanence_deatils'),
    path('mainmaintenance_pdf', views.mainmaintenance_pdf, name='mainmaintenance_pdf'),
    path('unplanned_maintanence', views.unplanned_maintanence, name='unplanned_maintanence'),
    path('unplanned_maintanence_pdf', views.unplanned_maintanence_pdf, name='unplanned_maintanence_pdf'),
    path('preventory_maintanence', views.preventory_maintanence, name='preventory_maintanence'),
    path('preventory_maintanence_pdf', views.preventory_maintanence_pdf, name='preventory_maintanence_pdf'),
    path('validation_calibration', views.validation_calibration, name='validation_calibration'),
    path('validation_calibration_pdf', views.validation_calibration_pdf, name='validation_calibration_pdf'),
    path('get_report', views.get_report, name='get_report'),
    path('ins_document', views.ins_document, name='ins_document'),
    path('email_sending', views.email_sending, name='email_sending'),
    path('send_email', views.send_email, name='send_email'),
    path('veryf_otp', views.veryf_otp, name='veryf_otp'),
    path('finalized_bill', views.finalized_bill, name='finalized_bill'),
    path('closed_bill', views.closed_bill, name='closed_bill'),
    path('cancel_bill', views.cancel_bill, name='cancel_bill'),
    path('cancel_bill_store/<pk>', views.cancel_bill_store, name='cancel_bill_store'),
    path('discharge_form', views.discharge_form, name='discharge_form'),
    path('case_summery', views.case_summery, name='case_summery'),
    path('consent_chemotherapy', views.consent_chemotherapy, name='consent_chemotherapy'),
    path('refferal_form', views.refferal_form, name='refferal_form'),
    path('print_consent_chemotherapy/<pk>', views.print_consent_chemotherapy, name='print_consent_chemotherapy'),
    path('print_refferal_form/<pk>', views.print_refferal_form, name='print_refferal_form'),
    path('print_case_summery/<pk>', views.print_case_summery, name='print_case_summery'),
    path('for_open_bill_main_opd', views.for_open_bill_main_opd, name='for_open_bill_main_opd'),
    path('discharge_list', views.discharge_list, name='discharge_list'),
    path('discharge_report/<pk>', views.discharge_report, name='discharge_report'),
    path('dep_lab_report_all', views.dep_lab_report_all, name='dep_lab_report_all'),
    path('dep_lab_report_print_all/<pk>', views.dep_lab_report_print_all, name='dep_lab_report_print_all'),
    path('send_email/<pk>', views.send_email, name='send_email'),
    path('discharge_reportopd/<str:pk>', views.discharge_reportopd, name='discharge_reportopd'),
    path('discharge_listopd', views.discharge_listopd, name='discharge_listopd'),
    path('list_dialysis_patient', views.list_dialysis_patient, name='list_dialysis_patient'),
    #========= Inventory Item Master =========================
    # path('inventory_itemmaster', views.inventory_itemmaster, name='inventory_itemmaster'),

###--Insurance Module---###
    path('checklist_master',views.checklist_master,name="checklist_master"),
    path('insurance_claim',views.insurance_claim,name="insurance_claim"),
    path('checklisted_bill',views.checklisted_bill,name="checklisted_bill"),
    path('claim_acknowledge/<bill_no>/',views.claim_acknowledge,name="claim_acknowledge"),
    path('raising_queries/<bill_no>/',views.raising_queries,name="raising_queries"),
    path('view_document_details/<bill_no>/',views.view_document_details,name="view_document_details"),
    path('raising_queries_list',views.raising_queries_list,name="raising_queries_list"),
    path('settled_claim_list',views.settled_claim_list,name="settled_claim_list"),
    path('acknowledge_claim',views.acknowledge_claim,name="acknowledge_claim"),
    path('payment_details_claim/<pk>/',views.payment_details_claim,name="payment_details_claim"),
    path('save_claim_settle',views.save_claim_settle,name="save_claim_settle"),
    path('queries_list/<bill_no>/',views.queries_list,name="queries_list"),

#==============nephromed pharmacy===================

# Gohila Inventory
    path('store_master',views.store_master),
    path('deleting_store_master/<id>',views.deleting_store_master),
    path('inventory_itemmaster',views.inventory_itemmaster),
    path('vendor_master',views.vendor_master , name='vendor_master'),
    path('item_category_master',views.item_category_master),
    path('packaging_master',views.packaging_master),
    path('item_unit_master',views.item_unit_master),
    path('load_itemcategory',views.load_itemcategory ,name='load_itemcategoryy'),
    path('itemsubcategory_master',views.itemsubcategory_master),


    # Pharmacy
    path('pharmacy_dashboard',pharmacyviews.pharmacy_dashboard,name="pharmacy_dashboard"),
    path('purchase_order',pharmacyviews.purchase_order,name="purchase_order"),
    path('PO_calculate',pharmacyviews.PO_calculate,name="calculate"),
    path('get_stock_details',pharmacyviews.get_stock_details,name="get_stock_details"),
    path('PO_preview',pharmacyviews.PO_preview,name="PO_preview"),
    path('PO_approval_preview',pharmacyviews.PO_approval_preview,name="PO_approval_preview"),
    path('purchase_order_approval',pharmacyviews.purchase_order_approval,name="purchase_order_approval"),
    path('PO_pending_update/<pk>/',pharmacyviews.PO_pending_update,name="PO_pending_update"),
    path('PO_approveview/<pk>/',pharmacyviews.PO_approveview,name="PO_approveview"),
    path('PO_update/',pharmacyviews.PO_update,name="PO_update"),
    path('email_sending',pharmacyviews.email_sending,name="email_sending"),
    path('stock_entry',pharmacyviews.stock_entry,name="stock_entry"),
    path('search_single_PO/<pk>/',pharmacyviews.search_single_PO,name="search_single_PO"),
    path('SE_preview',pharmacyviews.SE_preview,name="SE_preview"),
    path('Without_PO',pharmacyviews.SE_without_po,name="SE_without_po"),
    path('vendor_payment',pharmacyviews.vendor_payment,name="vendor_payment"),
    path('vendor_payment_js',pharmacyviews.vendor_payment_js,name="vendorpaymentjs"),
    path('item_issue_to_mainstore',pharmacyviews.item_issue_to_mainstore,name="item_issue_to_mainstore"),
    path('item_issue_tomainstore/<po_id>',pharmacyviews.item_issue_tomainstore,name="item_issue_tomainstore"),
    path('search_batch_intent_JQ',pharmacyviews.search_batch_intent_JQ,name="search_batch_intent_JQ"),
    path('material_indent',pharmacyviews.material_indent,name="material_intent"),
    path('meterial_intent_JS',pharmacyviews.meterial_intent_JS,name="meterial_intent_JS"),
    path('material_indent_approval',pharmacyviews.material_indent_approval,name="material_indent_approval"),
    path('material_indent_item_detail/<indent_id>',pharmacyviews.material_indent_item_detail,name="material_indent_item_detail"),
    path('materialindent_approve_item_detail/<indent_id>',pharmacyviews.materialindent_approve_item_detail,name="materialindent_approve_item_detail"),
    path('indent_inbox',pharmacyviews.indent_inbox,name="indent_inbox"),
    path('item_issue',pharmacyviews.item_issue,name="item_issue"),
    path('WO_intent',pharmacyviews.WO_intent,name="WO_intent"),
    path('without_JQ',pharmacyviews.without_JQ,name="without_JQ"),
    path('search_material_intent/<pk>/',pharmacyviews.search_material_intent,name="search_material_intent"),
    path('search_material_intent_JQ',pharmacyviews.search_material_intent_JQ,name="search_material_intent_JQ"),
    path('item_return',pharmacyviews.item_return,name="item_return"),
    path('item_return_JS',pharmacyviews.item_return_JS,name="itemreturnJS"),
    path('item_return_to_cpc',pharmacyviews.item_return_to_cpc,name="item_return_to_cpc"),
    path('return_to_cpc_js',pharmacyviews.return_to_cpc_js,name="return_to_cpc_js"),
    path('mainstore_makereturn',pharmacyviews.mainstore_makereturn,name="mainstore_makereturn"),
    path('item_return_supplier',pharmacyviews.item_return_supplier,name="item_return_supplier"),
    path('STV_makereturn',pharmacyviews.STV_makereturn,name="STV_makereturn"),
    path('purchase_intent',pharmacyviews.purchase_intent,name="purchase_intent"),
    path('purchase_intent_approval',pharmacyviews.purchase_intent_approval,name="purchase_intent_approval"),
    path('PI_pending_update/<pk>/',pharmacyviews.PI_pending_update,name="PI_pending_update"),
    path('PI_update',pharmacyviews.PI_update,name="PI_update"),
    path('make_PO_for_PI/',pharmacyviews.make_PO_for_PI,name="make_PO_for_PI"),
    path('PI_items_details/<pk>/',pharmacyviews.PI_items_details,name="PI_items_details"),
    path('Manual_stock_adjustment',pharmacyviews.manual_stock_adjustment,name="Manual_stock_adjustment"),
    path('Single_update_adjustment',pharmacyviews.Single_update_adjustment,name="Single"),
    path('file_upload',pharmacyviews.file_upload,name="fileupload"),
    path('PO_approval_sendmail',pharmacyviews.PO_approval_sendmail,name="mailsending"),
    path('return_to_supplier_js',pharmacyviews.return_to_supplier_js,name="returntosupplierjs"),
    path('patient_feedback',pharmacyviews.patient_feedback,name="patient_feedback"),
    path('get_uhid_detail',pharmacyviews.get_uhid_detail,name="get_uhid_detail"),
    path('patient_feedback_report',pharmacyviews.patient_feedback_report,name="patient_feedback_report"),
    path('viewPO_in_poapproval',pharmacyviews.viewPO_in_poapproval,name="viewPO_in_poapproval"),
    path('viewPO_details/<pk>/',pharmacyviews.viewPO_in_poapproval_details,name="viewPO_details"),
    path('department_consump_search',pharmacyviews.department_consump_search,name="department_consump_search"),
    path('department_consump',pharmacyviews.department_consump,name="department_consump"),
    path('save_department_consume',pharmacyviews.save_department_consume,name="save_department_consume"),
    path('transfer_indent',pharmacyviews.transfer_indent,name="transfer_indent"),
    path('stock_transfer',pharmacyviews.stock_transfer,name="stock_transfer"),
    path('search_transfer_intent/<pk>/',pharmacyviews.search_transfer_intent,name="search_transfer_intent"),
    path('transfer_request_tomainstore',pharmacyviews.transfer_request_tomainstore,name="transfer_request_tomainstore"),
    path('search_transfer_item_detail/<pk>/',pharmacyviews.search_transfer_item_detail,name="search_transfer_item_detail"),
    path('transfer_to_cpc',pharmacyviews.transfer_to_cpc,name="transfer_to_cpc"),
    path('request_transfer_item_list/<pk>/',pharmacyviews.request_transfer_item_list,name="request_transfer_item_list"),
    path('without_indent_stock_transfer',pharmacyviews.without_indent_stock_transfer,name="without_indent_stock_transfer"),
    path('searchbatchno_mainstore',pharmacyviews.searchbatchno_mainstore,name="searchbatchno_mainstore"),

    # pharmacy sales

    path('add_counter_saleout_patient',pharmacyviews.add_counter_saleout_patient,name="counter_saleout_patient"),
    path('add_count_sale_js',pharmacyviews.add_count_sale_js,name="add_count_sale"),
    path('payment_detail_sale',pharmacyviews.payment_detail_sale,name="payment_detail_sale"),
    path('prescription_details',pharmacyviews.prescription_details,name="prescription_details"),
    path('search_batchno',pharmacyviews.search_batchno,name="searchbatchno"),
    path('get_patientregistration_js',pharmacyviews.get_patientregistration_js,name="patientregistration"),
    path('add_counter_saleout_patient_preview',pharmacyviews.add_counter_saleout_patient_preview,name="saleoutpatientpreview"),
    path('sales_return_from_OP',pharmacyviews.sales_return_from_OP,name="sales_return_from_OP"),
    path('sales_return_from_OP_1',pharmacyviews.sales_return_from_OP_1,name="sales_return_from_OP_1"),
    path('sales_return_from_OP_invoice',pharmacyviews.sales_return_from_OP_invoice,name="sales_return_OPinvoice"),
    path('status_update_to_PS',pharmacyviews.status_update_to_PS,name="status_updatePS"),
    path('status_update_to_PSR',pharmacyviews.status_update_to_PSR,name="status_updatePSR"),

    path('department_consump_search',pharmacyviews.department_consump_search,name="department_consump_search"),
    path('department_consump',pharmacyviews.department_consump,name="department_consump"),
    # Pharmacy Reports

    path('item_status_report',pharmacyviews.item_status_report,name="item_status_report"),
    path('PO_report',pharmacyviews.PO_report,name="PO_report"),
    path('PO_report_pk/<pk>/',pharmacyviews.PO_report_pk,name="PO_report_pk"),
    path('batchwise_report',pharmacyviews.batchwise_report,name="batchwise_report"),
    path('po_status_report',pharmacyviews.po_status_report,name="po_status_report"),
    path('po_supplier_wise_search',pharmacyviews.po_supplier_wise_search,name="po_supplier_wise_search"),
    path('po_supplier_wise_report/<pk>',pharmacyviews.po_supplier_wise_report,name="po_supplier_wise_report"),
    path('po_aging_report',pharmacyviews.po_aging_report,name="po_aging_report"),
    path('po_item_details_report/<pk>',pharmacyviews.po_item_details_report,name="po_item_details_report"),
    path('item_issue_details/<pk>',pharmacyviews.item_issue_details,name="item_issue_details"),
    path('item_issue_report',pharmacyviews.item_issue_report,name="item_issue_report"),
    path('item_return_report',pharmacyviews.item_return_report,name="item_return_report"),
    path('op_sale_report',pharmacyviews.op_sale_report,name="op_sale_report"),
    path('op_sale_report_details/<pk>',pharmacyviews.op_sale_report_details,name="op_sale_report_details"),
    path('op_sale_return_report',pharmacyviews.op_sale_return_report,name="op_sale_return_report"),
    path('vendor_payment_report',pharmacyviews.vendor_payment_report,name="vendor_payment_report"),
    path('expiry_item_list_report',pharmacyviews.expiry_item_list_report,name="expiry_item_list_report"),
    path('department_consumption_report',pharmacyviews.department_consumption_report,name="department_consumption_report"),
    path('stock_movement_report',pharmacyviews.stock_movement_report,name="stock_movement_report"),
    path('itemwise_purchase_report',pharmacyviews.itemwise_purchase_report,name="itemwise_purchase_report"),
    path('item_status_with_particular',pharmacyviews.item_status_with_particular,name="item_status_with_particular"),
    path('detail_item_status_report',pharmacyviews.detail_item_status_report,name="detail_item_status_report"),
    path('grn_report',pharmacyviews.grn_report,name="grn_report"),
    path('grn_item_detail/<pk>/',pharmacyviews.grn_item_detail,name="grn_item_detail"),
    path('stock_adjustement_report',pharmacyviews.stock_adjustement_report,name="stock_adjustement_report"),
    path('pharmacysale_summary_report',pharmacyviews.pharmacysale_summary_report,name="pharmacysale_summary_report"),
    path('pharmacysale_detail_report',pharmacyviews.pharmacysale_detail_report,name="pharmacysale_detail_report"),
    path('stock_transfer_report',pharmacyviews.stock_transfer_report,name="stock_transfer_report"),
    path('stock_tranfer_items_list/<pk>',pharmacyviews.stock_tranfer_items_list,name="stock_tranfer_items_list"),
    path('item_issue_report_details/<pk>',pharmacyviews.item_issue_report_details,name="item_issue_report_details"),



#====================================================== Merging Code 29/03/2023==========================================
    path('list_cancel_bill', views.list_cancel_bill, name="list_cancel_bill"),
    path('vitals_sign', views.vitals_sign, name="vitals_sign"),


    path('location_master', views.location_master, name='location_master'),

    # RIS
    path('RIS_pendinginvestigation',views.RIS_pendinginvestigation,name='RIS_pendinginvestigation'),
    path('note_book/<pk>',views.note_book,name='note_book'),
    path('RIS_report',views.RIS_report,name='RIS_report'),
    path('RIS_report_print/<pk>',views.RIS_report_print,name='RIS_report_print'),

    path('final_bill',views.final_bill,name='final_bill'),
    path('template_master',views.template_master,name='template_master'),
    path('radiology_template_master',views.radiology_template_master,name='radiology_template_master'),
    path('lab_template_master',views.lab_template_master,name='lab_template_master'),
    path('radiology_template_master_edit/<pk>',views.radiology_template_master_edit,name='radiology_template_master_edit'),
    path('lab_template_master_edit/<pk>',views.lab_template_master_edit,name='lab_template_master_edit'),

    path('appointment_table', views.list_of_appointment, name='delete-appointment'),
    path('admin-dashboard',views.patient_dashboard),
    path('new-appointment',views.appointment_by_admin),
    path('choose-doctor',views.choose_doctor),
    path('booked-slots',views.booked_slots),
    path('successfully-booked',views.successfully_booked),
    path('appointment_patient_search',views.appointment_patient_search),
    path('permanent_access_master',views.permanent_access_master,name = "permanent_access_master"),
    path('edit_permanent_access_master/<pk>/',views.edit_permanent_access_master,name = "edit_permanent_access_master"),
    path('select_location', views.select_location, name='select_location'),
    path('change_password', views.change_password, name="change_password"),
    path('refered_bymaster', views.refered_bymaster, name="refered_bymaster"),
    path('edit_refered_bymaster/<pk>',views.edit_refered_bymaster,name = "edit_refered_bymaster"),

#====================================================== for dialysis 03/04/2023==========================================
    path('list_new_dialysis_patient', views.list_new_dialysis_patient, name='list_new_dialysis_patient'),
    path('prescription_dialysis/<str:pk>', views.prescription_dialysis, name='prescription_dialysis'),
    path('prescription_dialysis_update/<str:pk>', views.prescription_dialysis_update, name='prescription_dialysis_update'),
    path('temp_access', views.temp_access, name='temp_access'),
    path('prescription_dialysis_update1/<str:pk>',views.prescription_dialysis_update1,name = "prescription_dialysis_update1"),
    path('temp_access_delete',views.temp_access_delete,name = "temp_access_delete"),
]
